package model.hibernate;

// Generated Nov 7, 2015 12:57:09 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private int id;
	private String name;
	private String quantity;
	private String scaleType;
	private String imagePath;
	private String category;
	private Set productsInStores = new HashSet(0);

	public Products() {
	}

	public Products(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Products(int id, String name, String quantity, String scaleType,
			String imagePath, String category, Set productsInStores) {
		this.id = id;
		this.name = name;
		this.quantity = quantity;
		this.scaleType = scaleType;
		this.imagePath = imagePath;
		this.category = category;
		this.productsInStores = productsInStores;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	public String getScaleType() {
		return this.scaleType;
	}

	public void setScaleType(String scaleType) {
		this.scaleType = scaleType;
	}

	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Set getProductsInStores() {
		return this.productsInStores;
	}

	public void setProductsInStores(Set productsInStores) {
		this.productsInStores = productsInStores;
	}

}
