package model.hibernate;

// Generated Nov 7, 2015 12:57:09 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ProductsInStore generated by hbm2java
 */
public class ProductsInStore implements java.io.Serializable {

	private int id;
	private Products products;
	private Stores stores;
	private String quantity;
	private String productCode;
	private Set productsInStorePriceses = new HashSet(0);

	public ProductsInStore() {
	}

	public ProductsInStore(int id) {
		this.id = id;
	}

	public ProductsInStore(int id, Products products, Stores stores,
			String quantity, String productCode, Set productsInStorePriceses) {
		this.id = id;
		this.products = products;
		this.stores = stores;
		this.quantity = quantity;
		this.productCode = productCode;
		this.productsInStorePriceses = productsInStorePriceses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Stores getStores() {
		return this.stores;
	}

	public void setStores(Stores stores) {
		this.stores = stores;
	}

	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	public Set getProductsInStorePriceses() {
		return this.productsInStorePriceses;
	}

	public void setProductsInStorePriceses(Set productsInStorePriceses) {
		this.productsInStorePriceses = productsInStorePriceses;
	}

}
