package model.hibernate;

// Generated Nov 7, 2015 12:57:09 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Stores generated by hbm2java
 */
public class Stores implements java.io.Serializable {

	private int id;
	private String name;
	private Set productsInStores = new HashSet(0);

	public Stores() {
	}

	public Stores(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Stores(int id, String name, Set productsInStores) {
		this.id = id;
		this.name = name;
		this.productsInStores = productsInStores;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getProductsInStores() {
		return this.productsInStores;
	}

	public void setProductsInStores(Set productsInStores) {
		this.productsInStores = productsInStores;
	}

}
